# This file was generated by GoReleaser. DO NOT EDIT.
cask "doppler" do
  version "3.76.4"

  on_macos do
    on_intel do
      sha256 "b1ada08828442d6cc21636329ec66b2b20252dd22bfb19ff2d887b003750b6cf"
      url "https://github.com/DopplerHQ/cli/releases/download/#{version}/doppler_#{version}_macOS_amd64.tar.gz",
        verified: "github.com/DopplerHQ/cli"
    end
    on_arm do
      sha256 "3a7e42461bae88a7e26ed8cc12a20f0834d477c64d0a9b3416aa49743f0492c2"
      url "https://github.com/DopplerHQ/cli/releases/download/#{version}/doppler_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/DopplerHQ/cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a3640467f1365028b8bd41679384dad1ab72a40cb0b027d371e7e39e4a29d9b"
      url "https://github.com/DopplerHQ/cli/releases/download/#{version}/doppler_#{version}_linux_amd64.tar.gz",
        verified: "github.com/DopplerHQ/cli"
    end
    on_arm do
      sha256 "87c80d4e44dfd7b25012c8545b69203ed166a58e5b3d7b43bb7de90f5651efea"
      url "https://github.com/DopplerHQ/cli/releases/download/#{version}/doppler_#{version}_linux_arm64.tar.gz",
        verified: "github.com/DopplerHQ/cli"
    end
  end

  name "doppler"
  desc "The official Doppler CLI for managing your secrets"
  homepage "https://doppler.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "doppler"
  bash_completion "completions/doppler.bash"
  fish_completion "completions/doppler.fish"
  zsh_completion "completions/doppler.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/doppler"]
    end
  end

  # No zap stanza required

end
