# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doppler < Formula
  desc "The official Doppler CLI for managing your secrets"
  homepage "https://doppler.com"
  version "3.53.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DopplerHQ/cli/releases/download/3.53.0/doppler_3.53.0_macOS_arm64.tar.gz"
      sha256 "ff04a7515c6fb1d0b50737e541b40836006004c6b62de3b6e9574314bd19f4f4"

      def install
        bin.install "doppler"
        bash_completion.install "completions/doppler.bash" => "doppler"
        zsh_completion.install "completions/doppler.zsh" => "_doppler"
        fish_completion.install "completions/doppler.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DopplerHQ/cli/releases/download/3.53.0/doppler_3.53.0_macOS_amd64.tar.gz"
      sha256 "a0b4d9c997d6b3a5e06db305d524a135497086dcb1bcdb8287538ed150405e5e"

      def install
        bin.install "doppler"
        bash_completion.install "completions/doppler.bash" => "doppler"
        zsh_completion.install "completions/doppler.zsh" => "_doppler"
        fish_completion.install "completions/doppler.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/DopplerHQ/cli/releases/download/3.53.0/doppler_3.53.0_linux_armv6.tar.gz"
      sha256 "a06f13e4fbcd63c8a8f73c1670b733b747ca20c3ce4ac05f0438a16b56a7730d"

      def install
        bin.install "doppler"
        bash_completion.install "completions/doppler.bash" => "doppler"
        zsh_completion.install "completions/doppler.zsh" => "_doppler"
        fish_completion.install "completions/doppler.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DopplerHQ/cli/releases/download/3.53.0/doppler_3.53.0_linux_amd64.tar.gz"
      sha256 "ac86482fa4501061aa8fd0185caa3a71b97e709d30a53a7edcffc4d9f0ae736b"

      def install
        bin.install "doppler"
        bash_completion.install "completions/doppler.bash" => "doppler"
        zsh_completion.install "completions/doppler.zsh" => "_doppler"
        fish_completion.install "completions/doppler.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DopplerHQ/cli/releases/download/3.53.0/doppler_3.53.0_linux_arm64.tar.gz"
      sha256 "8bfc511658bbc55a57a3e5f965f3837eaaeafd8d6fadac9c18db8c14f2966862"

      def install
        bin.install "doppler"
        bash_completion.install "completions/doppler.bash" => "doppler"
        zsh_completion.install "completions/doppler.zsh" => "_doppler"
        fish_completion.install "completions/doppler.fish"
      end
    end
  end

  test do
    system "#{bin}/doppler --version"
  end
end
