# This file was generated by GoReleaser. DO NOT EDIT.
class Dopplerhq < Formula
  desc "Doppler helps manage your secrets and config across all your projects."
  homepage "https://doppler.com"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/DopplerHQ/cli/releases/download/v0.0.5/cli_0.0.5_Darwin_x86_64.tar.gz"
    sha256 "a9723fadd2c2cc57b84bf49d55d484c9fd6e5705a386bf53574e5da072faaad7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/DopplerHQ/cli/releases/download/v0.0.5/cli_0.0.5_Linux_x86_64.tar.gz"
      sha256 "c77cb79f888463b63e536774417f819d26228d73f2977bd33af1d13302834b3a"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DopplerHQ/cli/releases/download/v0.0.5/cli_0.0.5_Linux_arm64.tar.gz"
        sha256 "813eef89035b6fa271bad9a8ac79bad2ab65505236fef8e94df45eaf73e5e4a0"
      else
        url "https://github.com/DopplerHQ/cli/releases/download/v0.0.5/cli_0.0.5_Linux_armv6.tar.gz"
        sha256 "9724600925df5e4f6b292ac944f9e56c066833f29e3c0443c736051864e44b9d"
      end
    end
  end

  def install
    bin.install "doppler"
  end
end
